In [1]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time

# Numpy Vs Torch

Pytorch es un opaquete es nos permitirá a los usuarios crear entornos de entramiento de los estados creados en machinearning/deep learning, además, lo utilizaremos para simplificar el tiempo de calculo de los procesores utilziados.

In [32]:
#Numpy Vs Torch

n = np.linspace(0,1,5)   #Crea un array
t = torch.linspace(0,1,5)   #Crea un tensor


In [33]:
n

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
t

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [39]:
#Se puede redefinir su tamaño de forma similar:


#np.arange(x), permite crear x elementos.

n = np.arange(48).reshape(3,4,4)     #Primer término: np.arange(x), indica el número de elementos que tendrá el array.
t = torch.arange(48).reshape(3,4,4)  #Primer término: reshape(x,y,y) indica el número de divisiones que tendra el array y cómo se acomodará.
                                     #Hay que tener en cuenta que 48=3*4*4
                                     #reshape(x,0,0): indica la dimensión del array
                                     #reshape(0,x,0): indica las divisiones del array
                                     #reshape(0,0,x): indica los numeros de elemntos por divisiones en el array.
    

In [36]:
n

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [37]:
t

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],

        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]])

Es importante tener en cuenta que, ambas librerias tienes las mismas reglas de transmisión o "Broadcasting rules".
Estas reglas se hablaran a continuación y se usan para trabjar de manera más eficiente con esta libreria.

# Reglas Generales de Transmisión - Broadcasting Rules

Cuando se operan con dos arrays, NumPy realizar la comparación de la forma de sus elementales.
Este empieza con la dimensionan final (empezando en la derecha) y trabajando hacia la izquierda. Dos dimensiones son compatibles sii:
* Son iguales, o
* Una de ellas es igual a 1.

*A continuacion de presenta un ejemplo*: Las dos siguientes son iguales:

6-D array

Shape 1: (1,6,4,1,7,2)    

Shape 2: (5,6,1,3,1,2)


In [48]:
a = np.ones((6,5))

In [97]:
a.shape

(6, 5)

In [49]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
b = np.arange(5).reshape(1,5)

In [98]:
b.shape

(1, 5)

In [95]:
b

array([[0, 1, 2, 3, 4]])

Vemos que tanto a como b cumplen la regla de Broadcasting, y pueden operar aritmericamente entre ellas.

In [99]:
a+b

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

Manera similar para pytorch.

In [100]:
a = torch.ones((6,5))

In [101]:
a.shape

torch.Size([6, 5])

In [102]:
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [103]:
b = torch.arange(5).reshape((1,5))

In [104]:
b.shape

torch.Size([1, 5])

In [105]:
b

tensor([[0, 1, 2, 3, 4]])

In [106]:
a+b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])

Ejemplo: Esaclar cada canal de color de un canal por una cantidad diferente:

Image (3d array): 256 x 256 x 3 

Scale (1d array):           x 3 

Result (3d array):256 x 256 x 3

In [123]:
Image = torch.randn((256,256,3))
Scale = torch.tensor([0.5,1.5,1])

In [124]:
Image

tensor([[[-0.4380, -0.0646,  1.1617],
         [ 1.9910,  2.6149, -0.7018],
         [ 0.7084,  0.2115,  0.2887],
         ...,
         [-0.0531,  1.7332, -1.8491],
         [-0.1330, -0.0340,  1.0178],
         [ 0.3894,  0.8846,  0.8746]],

        [[-1.3944, -1.2168, -0.3124],
         [-1.4399,  0.0253,  1.2241],
         [ 1.2480, -0.8514, -1.9048],
         ...,
         [-0.6295, -0.0271,  0.9641],
         [-0.6879, -1.3520, -0.7752],
         [ 1.8647, -1.7098, -1.7209]],

        [[-0.3068, -2.1579, -1.1805],
         [-0.7247,  0.9899, -0.9158],
         [-0.0480,  1.4102, -1.7402],
         ...,
         [ 1.4566,  1.1486,  0.0396],
         [ 1.1208, -1.0850, -0.8937],
         [-0.4337,  0.1638,  0.1576]],

        ...,

        [[ 0.9731,  0.0742, -1.2102],
         [ 1.7489, -0.9656,  0.7161],
         [-0.1075, -0.4320, -1.0777],
         ...,
         [-0.1369,  1.1503, -0.6220],
         [-1.5659, -0.5805, -0.0238],
         [-0.5006,  0.6346, -0.6074]],

        [[

In [125]:
Scale

tensor([0.5000, 1.5000, 1.0000])

In [126]:
Result = Image*Scale

In [127]:
Result

tensor([[[-0.2190, -0.0969,  1.1617],
         [ 0.9955,  3.9224, -0.7018],
         [ 0.3542,  0.3172,  0.2887],
         ...,
         [-0.0266,  2.5999, -1.8491],
         [-0.0665, -0.0510,  1.0178],
         [ 0.1947,  1.3269,  0.8746]],

        [[-0.6972, -1.8253, -0.3124],
         [-0.7200,  0.0379,  1.2241],
         [ 0.6240, -1.2771, -1.9048],
         ...,
         [-0.3148, -0.0406,  0.9641],
         [-0.3440, -2.0280, -0.7752],
         [ 0.9323, -2.5647, -1.7209]],

        [[-0.1534, -3.2368, -1.1805],
         [-0.3624,  1.4848, -0.9158],
         [-0.0240,  2.1153, -1.7402],
         ...,
         [ 0.7283,  1.7228,  0.0396],
         [ 0.5604, -1.6274, -0.8937],
         [-0.2169,  0.2457,  0.1576]],

        ...,

        [[ 0.4866,  0.1113, -1.2102],
         [ 0.8745, -1.4484,  0.7161],
         [-0.0537, -0.6480, -1.0777],
         ...,
         [-0.0684,  1.7255, -0.6220],
         [-0.7830, -0.8707, -0.0238],
         [-0.2503,  0.9520, -0.6074]],

        [[

# Terminal de Pruebas

In [51]:
import numpy as np

In [68]:
x = np.array(3)

In [69]:
x

array(3)

In [70]:
y = np.array(7)

In [71]:
y

array(7)

In [72]:
x*y

21

In [75]:
x = np.array([3])

In [76]:
y = np.array([7])

In [77]:
x*y

array([21])

In [55]:
x1 = np.array(2)

In [56]:
x1

array(2)

In [133]:
x1= torch.tensor((3,3,3))

In [134]:
x

tensor([3, 3, 3])

In [135]:
x2 = torch.tensor([3,3,3])

In [136]:
x

tensor([3, 3, 3])

In [137]:
x1 == x2

tensor([True, True, True])

In [142]:
torch.randn((5,2,3))

tensor([[[-0.4669,  1.4576, -2.6692],
         [-0.5733, -0.0362,  0.6935]],

        [[ 0.1292, -0.4471, -1.9122],
         [-0.0876, -0.4642, -0.9346]],

        [[-0.6746, -0.4166,  0.8815],
         [-0.9591,  1.4819, -2.2322]],

        [[-0.3944, -0.0707, -0.2502],
         [-0.1049,  2.3924,  0.9855]],

        [[-0.3656, -0.7815,  0.6114],
         [-0.7343,  1.2421, -2.4393]]])