In [1]:
# Se discute la importancia del Numpy

In [2]:
import numpy as np

In [3]:
a = [1,2,3]
b = [2,4,6]

a+b

[1, 2, 3, 2, 4, 6]

In [7]:
np_a = np.array(a)
np_b = np.array(b)
np_a + np_b

array([3, 6, 9])

In [8]:
np_a.dtype

dtype('int32')

In [9]:
np_a

array([1, 2, 3])

In [10]:
np_a[0] = 13.3456

In [19]:
np_a  #Vemos que el array solo es de enteros y no almacena el numero completo ingresado

array([13.3456,  2.    ,  3.    ])

In [12]:
np_a.dtype

dtype('int32')

In [13]:
np_a = np.array([1,2,3], dtype ='float')

In [14]:
np_a

array([1., 2., 3.])

In [15]:
np_a.dtype

dtype('float64')

In [16]:
np_a[0] = 13.3456

In [29]:
np_a  #Vemos que aquí si almacena la varaible

array([13.3456,  2.    ,  3.    ])

In [30]:
#Empieza a mencionar las funciones universales

In [31]:
np.sin(np_a)

array([0.70273137, 0.90929743, 0.14112001])

In [32]:
np.cos(np_b)

array([-0.41614684, -0.65364362,  0.96017029])

In [33]:
type(np_a) #Array n-dimensional

numpy.ndarray

In [34]:
lol = [[1,2,3],[4,5,6]]
type(lol)

list

In [35]:
np_array = np.array(lol)

In [36]:
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
lol[1]

[4, 5, 6]

In [38]:
lol[1][1]  #Dos corchetes para acceder a la información

#No funciona:
# lol[1,1]

5

In [39]:
np_array[1,1]  #Aqui si funciona

5

In [40]:
np_array[1][1] #También funciona

5