In [1]:
#Librerias
import numpy as np


#Método de eliminación de Gauus
Para una matrix 3*3.


```
A=([[a_11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
```
Que visualmente seria:
\begin{equation}
\begin{matrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{matrix}
\end{equation} 

También se puede ver en python con la libreria y el siguiente código:


```
from sympy.matrices import *
A=Matrix([[-9,2],[10,14]]) 
A
 
```
Que nos da una matrix de 2*2.

In [2]:
2#A=Matrix([[-9,2],[10,14]]) 
#A

2

Ahora miremos un ejemplo, con una matrix 3*3, vamos a representar los primeros dos pasos de la eliminación de Gauss

In [15]:
#Sea B la matrix 3*3
B_1=np.array([1,2,1,1])
B_2=np.array([-1,1,3,1])
B_3=np.array([0,3,1,-1])


#B=Matrix([B_1,B_2,B_3])
B

array([ 1,  2, -3])

In [4]:
#Haciendo la primera reducción de Gauss.
B_2 = B_1+B_2 
B_2

array([0, 3, 4, 2])

In [5]:
#B=Matrix([B_1,B_2,B_3])
#B

Realizar el código de Gauss con el pseudo código del libro.

In [6]:
#Gausss Eliminación gaussiana
def gauss(A,b):
  n= len(b)
  for k in range(n-1):
    for i in range(k+1,n):
      factor = A[i][k]/A[k][k]
      for j in range(k,n):
        A[i][j]=A[i][j]-factor*A[k][j]
      b[i]=b[i]-factor*b[k]
  return A,b

In [7]:
A=[[1,2,1],[-1,1,3],[0,3,1]]
A

[[1, 2, 1], [-1, 1, 3], [0, 3, 1]]

In [10]:
gauss(A,B)

([[1, 2, 1], [0.0, 3.0, 4.0], [0.0, 0.0, -3.0]], [1, 2.0, -3.0])

In [11]:
#Con numpy
def gauss2(A,b):
  n= np.size(b)
  for k in range(n-1):
    for i in range(k+1,n):
      factor = A[i][k]/A[k][k]
      A[i]=A[i]-factor*A[k]
      b[i]=b[i]-factor*b[k]
  return A,b

In [12]:
A=np.array([[1,2,1],[-1,1,3],[0,3,1]])
B=np.array([1,1,-1])

In [13]:
gauss2(A,B)

(array([[ 1,  2,  1],
        [ 0,  3,  4],
        [ 0,  0, -3]]), array([ 1,  2, -3]))

Gauss internet


In [16]:
#Eliminación Gaussiana
#Función para mostrar la matriz

def mostrarMatriz(matriz,orden):
	for i in range(0,orden):
		linea = "| "
		for j in range(orden+1):
			linea +=  str(matriz[i][j])+" "
		linea += "| "
		print(linea)	
			
matriz = [[3,2,3,3], [1,3,1,-6], [5,1,3,12]]
#Orden de la matriz
orden=len(matriz) 
mostrarMatriz(matriz,orden);    
#Recorrer la matriz 
for j in range(0,orden+1):
	for i in range(0, orden):
		if i>j:
			#Divir los elementos de la matriz
			division=matriz[i][j]/matriz[j][j]
			for k in range(0, orden+1):
				#Obterner el nuevo valor para los elementos en la diagonal inferior
				matriz[i][k]=matriz[i][k]-division*matriz[j][k];
#Recorrer la matriz
x = [0,0,0]
for i in range(orden,0,-1):
	suma=0
	for j in range(i,orden):
		suma=suma+matriz[i-1][j]*x[j]
	#Obtener los valores de las variables
	x[i-1]=((matriz[i-1][orden]-suma)/matriz[i-1][i-1])	
#Mostrar los valores de las variables
for i in range(0,orden):
	print("x"+str(i)+" = "+str(x[i]))

| 3 2 3 3 | 
| 1 3 1 -6 | 
| 5 1 3 12 | 
x0 = 3.0
x1 = -3.0
x2 = -0.0


Gauss otro internet

In [17]:
# Método de Gauss
# Solución a Sistemas de Ecuaciones
# de la forma A.X=B

import numpy as np

# INGRESO
A = np.array([[4,2,5],
              [2,5,8],
              [5,4,3]])

B = np.array([[60.70],
              [92.90],
              [56.30]])

# PROCEDIMIENTO
casicero = 1e-15 # Considerar como 0

# Evitar truncamiento en operaciones
A = np.array(A,dtype=float) 

# Matriz aumentada
AB  = np.concatenate((A,B),axis=1)
AB0 = np.copy(AB)

# Pivoteo parcial por filas
tamano = np.shape(AB)
n = tamano[0]
m = tamano[1]

# Para cada fila en AB
for i in range(0,n-1,1):
    # columna desde diagonal i en adelante
    columna  = abs(AB[i:,i])
    dondemax = np.argmax(columna)
    
    # dondemax no está en diagonal
    if (dondemax !=0):
        # intercambia filas
        temporal = np.copy(AB[i,:])
        AB[i,:] = AB[dondemax+i,:]
        AB[dondemax+i,:] = temporal
AB1 = np.copy(AB)

# eliminación hacia adelante
for i in range(0,n-1,1):
    pivote   = AB[i,i]
    adelante = i + 1
    for k in range(adelante,n,1):
        factor  = AB[k,i]/pivote
        AB[k,:] = AB[k,:] - AB[i,:]*factor

# sustitución hacia atrás
ultfila = n-1
ultcolumna = m-1
X = np.zeros(n,dtype=float)

for i in range(ultfila,0-1,-1):
    suma = 0
    for j in range(i+1,ultcolumna,1):
        suma = suma + AB[i,j]*X[j]
    b = AB[i,ultcolumna]
    X[i] = (b-suma)/AB[i,i]

X = np.transpose([X])


# SALIDA
print('Matriz aumentada:')
print(AB0)
print('Pivoteo parcial por filas')
print(AB1)
print('eliminación hacia adelante')
print(AB)
print('solución: ')
print(X)

Matriz aumentada:
[[ 4.   2.   5.  60.7]
 [ 2.   5.   8.  92.9]
 [ 5.   4.   3.  56.3]]
Pivoteo parcial por filas
[[ 5.   4.   3.  56.3]
 [ 2.   5.   8.  92.9]
 [ 4.   2.   5.  60.7]]
eliminación hacia adelante
[[ 5.    4.    3.   56.3 ]
 [ 0.    3.4   6.8  70.38]
 [ 0.    0.    5.   40.5 ]]
solución: 
[[2.8]
 [4.5]
 [8.1]]


oro método
